name: ClansAPI
version: '${project.version}'
main: me.vineer.clansapi.ClansAPI
api-version: 1.17
authors: [ Vineer ]
softdepend:
  - Essentials
  - LuckPerms
  - WorldEdit
commands:
  clan:
    description: clans
    usage: /<command>
